# Generated by Django 5.0.4 on 2024-04-09 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_address', models.CharField(blank=True, max_length=200, null=True)),
                ('ethereum_address', models.CharField(blank=True, max_length=200, null=True)),
                ('usdt_address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
    ]
