# Generated by Django 5.0.4 on 2024-04-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='transaction',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Available', 'Available'), ('Processing', 'Processing')], default='Pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(blank=True, choices=[('Rookie', 'Rookie $100 - $200'), ('Captain', 'Captain $210 - $500'), ('Veteran', 'Veteran $510 - ∞')], max_length=200, null=True),
        ),
    ]
